spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: dong
    url: jdbc:mysql://127.0.0.1:3306/dc?useSSL=false&useUnicode=true&characterEncoding=UTF-8

  jpa:
    show-sql: true
server:
  port: 8763
env:
  dev1
